name: Node.js CI Pipeline

# Trigger the workflow on push to the main branch or pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment (specify the Node.js version you need)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can specify the version you need

    # Install dependencies (e.g., using npm)
    - name: Install dependencies
      run: npm install

    # Run tests (using npm test)
    - name: Run tests
      run: npm test
