name: Java CI

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (JDK 11)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use Java 11
        distribution: 'temurin'  # Specify JDK distribution (Temurin is a good choice)

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: |
        mvn clean install  # Run Maven to build the project

    # Step 4: Run tests with Maven
    - name: Run tests with Maven
      run: mvn test  # Runs JUnit tests
