name: Java CI

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (JDK)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can specify any version like 8, 11, 16, etc.

    # Step 3: Build the project using Maven (or Gradle if you prefer)
    - name: Build with Maven
      run: |
        mvn clean install  # You can use `mvn package` if you don't want to install

    # Step 4: Run the tests using Maven
    - name: Run tests with Maven
      run: mvn test  # This will automatically run your JUnit tests
